---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

  tasks:
    - name: Install build-dependencies
      apt:
        name:
          - pbuilder
          - quilt
          - git-buildpackage
          - dput-ng
          - openssh-client
          - debhelper
          - dh-systemd
        state: latest
        update_cache: yes
      become: yes
    - name: Setup pbuilder base sid archive
      command: pbuilder create --distribution sid --debootstrapopts --variant=buildd creates=/var/cache/pbuilder/base.tgz
      become: yes
    - name: Update pbuilder sid archive
      command: pbuilder update --distribution sid
      become: yes
